# With `geom_gcn_preprocess` set to `False`

In [33]:
import torch 
from torch_geometric.datasets import WikipediaNetwork
from torch_geometric.data import Data

D1 = []

datasets = ["chameleon", "squirrel", "crocodile"]
for dataset in datasets:
    data = WikipediaNetwork(root=f'.\\tmp\\Wikipedia1\\{dataset}', name = f"{dataset}", geom_gcn_preprocess=False) ##### IMP: geom_gcn_preprocess = False
    data = data[0]
    print(data)
    D1.append(data)

Data(x=[2277, 128], edge_index=[2, 62792], y=[2277])
Data(x=[5201, 128], edge_index=[2, 396846], y=[5201])
Data(x=[11631, 128], edge_index=[2, 341691], y=[11631])


![image](geom_gcn_preprocess.png)

In [34]:
D1[0].x, D1[0].y # Continuous features and labels

(tensor([[-2.9467e-01, -8.0566e-02, -1.5377e-01,  ..., -1.2768e-01,
          -1.5202e-01, -1.6299e-01],
         [-2.0747e-01, -8.0566e-02, -1.5377e-01,  ..., -1.2768e-01,
          -1.5202e-01, -1.6299e-01],
         [-2.9467e-01, -8.0566e-02, -1.5377e-01,  ..., -1.2768e-01,
          -1.5202e-01, -1.6299e-01],
         ...,
         [-2.9467e-01,  6.5435e-03, -1.5377e-01,  ..., -1.2768e-01,
          -1.5202e-01, -1.6299e-01],
         [-2.0887e-01, -8.0566e-02, -1.5377e-01,  ...,  1.1396e+01,
          -1.5202e-01, -1.6299e-01],
         [-2.9467e-01, -8.0566e-02, -1.5377e-01,  ..., -1.2768e-01,
          -8.3011e-02, -1.6299e-01]]),
 tensor([ 5.1475,  8.9984,  9.0559,  ...,  4.6052, 10.0388,  5.6240]))

# With `geom_gcn_preprocess` set to `True`

In [7]:
import torch 
from torch_geometric.datasets import WikipediaNetwork
from torch_geometric.data import Data

D2 = []

datasets = ["chameleon", "squirrel"]
for dataset in datasets:
    data = WikipediaNetwork(root=f'.\\tmp\\Wikipedia2\\{dataset}', name = f"{dataset}", geom_gcn_preprocess=True) ##### IMP: geom_gcn_preprocess = True
    data = data[0]
    print(data)
    D2.append(data)

Data(x=[2277, 2325], edge_index=[2, 36101], y=[2277], train_mask=[2277, 10], val_mask=[2277, 10], test_mask=[2277, 10])
Data(x=[5201, 2089], edge_index=[2, 217073], y=[5201], train_mask=[5201, 10], val_mask=[5201, 10], test_mask=[5201, 10])


In [8]:
D2[0].x, D2[0].y

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 tensor([0, 3, 3,  ..., 0, 4, 0]))

In [45]:
print(torch.sum(D2[0].x[0, :])) ## Very sparse feature vector (seems discrete)
print(torch.unique(D2[0].y)) # 5 Discrete classes for Chameleon dataset
print(torch.cat([D2[0].train_mask[0, :].view(1, -1), D2[0].val_mask[0, :].view(1, -1), D2[0].test_mask[0, :].view(1, -1)], axis = 0)) # Disjoint division of 10 'things' for each sample accross train, val and test

tensor(7.)
tensor([0, 1, 2, 3, 4])
tensor([[False, False,  True,  True,  True, False,  True,  True, False,  True],
        [ True,  True, False, False, False,  True, False, False,  True, False],
        [False, False, False, False, False, False, False, False, False, False]])
